[server]
headless = true
port = 10000

[browser]
serverAddress = "0.0.0.0"
serverPort = 10000
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F5"
textColor = "#262730"
font = "sans serif"

[global]
maxCachedMessageSize = 1048576 # 1MB